version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  task:
    image: task:latest
    container_name: task
    build: ./src/task
    environment:
       - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
  worker:
    image: worker:latest
    container_name: worker
    build: ./src/worker
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq